-- register modded weapons options by adding them to tables below

-- loadout tables : we copy the gun into the loadout table from the main primary/secondary tables after adding it there
-- if there's nothing in the loadout table selected, will pull from the main table
-- primary & secondary work as expected, primaryspecial and secondaryspecial will both replace the primary weapon - to allow for example SMGs held like pistols as primary weapons

require "BanditWeapons"

BanditWeapons.CivilianPrimary = BanditWeapons.CivilianPrimary or {}
BanditWeapons.CivilianPrimarySpecial = BanditWeapons.CivilianPrimary or {}
BanditWeapons.CivilianSecondary = BanditWeapons.CivilianSecondary or {}
BanditWeapons.CivilianSecondarySpecial = BanditWeapons.CivilianSecondary or {}

BanditWeapons.PolicePrimary = BanditWeapons.PolicePrimary or {}
BanditWeapons.PolicePrimarySpecial = BanditWeapons.PolicePrimarySpecial or {}
BanditWeapons.PoliceSecondary = BanditWeapons.PoliceSecondary or {}
BanditWeapons.PoliceSecondarySpecial = BanditWeapons.PoliceSecondary or {}

BanditWeapons.MilitaryPrimary = BanditWeapons.MilitaryPrimary or {}
BanditWeapons.MilitaryPrimarySpecial = BanditWeapons.MilitaryPrimarySpecial or {}
BanditWeapons.MilitarySecondary = BanditWeapons.MilitarySecondary or {}
BanditWeapons.MilitarySecondarySpecial = BanditWeapons.MilitarySecondary or {}

BanditWeapons.ExoticPrimary = BanditWeapons.ExoticPrimary or {}
BanditWeapons.ExoticPrimarySpecial = BanditWeapons.ExoticPrimarySpecial or {}
BanditWeapons.ExoticSecondary = BanditWeapons.ExoticSecondary or {}
BanditWeapons.ExoticSecondarySpecial = BanditWeapons.ExoticSecondarySpecial or {}

BanditWeapons.LootedPrimary = BanditWeapons.LootedPrimary or {}
BanditWeapons.LootedPrimarySpecial = BanditWeapons.LootedPrimarySpecial or {}
BanditWeapons.LootedSecondary = BanditWeapons.LootedSecondary or {}
BanditWeapons.LootedSecondarySpecial = BanditWeapons.LootedSecondarySpecial or {}
	print ("test loading 123456789")
	
--basic weapons tables, other classes will use all available
table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[1])
table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[1])
table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[2])

table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[1])
table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[2])
table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[1])
table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[1])
table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[2])
	
if getActivatedMods():contains("\\Real Firearms") then		--b42/b41
	print ("loading real firearms")	

	--handgun
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol", "Base.9mmClip", 15, "M9Shoot", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RF_BrowningHighPower", "Base.RF_BrowningHighPowermag", 13, "RF_BrowningHighPower_Shoot", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol2", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol3", "Base.44Clip", 8, "DesertEagleShoot", 45))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RF_PB", "Base.RF_PBmag", 8, "RF_PB_Shoot", 35))	
	
	--semi auto
							
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_FG42", "Base.RF_FG42mag", 20, "RF_FG42_Shoot", 17))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_M1Garand", "Base.RF_M1Garandmag", 8, "RF_M1Garand_Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle2", "Base.M14Clip", 20, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_M110", "Base.RF_M110mag", 20, "RF_M110_Shoot", 38))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_SVD", "Base.RF_SVDmag", 10, "RF_SVD_Shoot", 38))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							
	--1h SMG						
	
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RF_Glock18", "Base.RF_Glock18mag", 17, "RF_Glock18_Shoot", 10))
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RF_MAC10", "Base.RF_MAC10mag", 30, "RF_MAC10_Shoot", 10))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RF_VECTOR", "Base.RF_VECTORmag", 50, "RF_VECTOR_Shoot", 9))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	
	--SMG
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_MP5SD", "Base.RF_MP5SDmag", 30, "RF_MP5SD_Shoot", 15))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_PPBizon", "Base.RF_PPBizonmag", 64, "RF_PPBizon_Shoot", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
	--auto rifle
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_Colt723", "Base.RF_Colt723mag", 30, "RF_Colt723_Shoot", 12))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_HK416A5", "Base.RF_HK416A5mag", 30, "RF_HK416A5_Shoot", 12))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_HoneyBadger", "Base.RF_HoneyBadgermag", 30, "RF_HoneyBadger_Shoot", 12))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_M4A1", "Base.RF_M4A1mag", 30, "RF_M4A1_Shoot", 12))
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_SIGSG552", "Base.RF_SIGSG552mag", 30, "RF_SIGSG552_Shoot", 12))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_FAL", "Base.RF_FALmag", 20, "RF_FAL_Shoot", 17))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])		
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_Mk14EBR", "Base.RF_Mk14EBRmag", 20, "RF_Mk14EBR_Shoot", 17))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])		
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_Mk17", "Base.RF_Mk17mag", 20, "RF_Mk17_Shoot", 18))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])	
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_Mk20", "Base.RF_Mk20mag", 20, "RF_Mk20_Shoot", 18))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_AK47", "Base.RF_AK47mag", 30, "RF_AK47_Shoot", 17))		
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])		
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_81-1", "Base.RF_RF_81-1mag", 30, "RF_RF_81-1_Shoot", 17))		
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])		
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_BAR", "Base.RF_BARmag", 20, "RF_BAR_Shoot", 19))		
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])				
	
	--mg
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_M249", "Base.RF_M249mag", 100, "RF_M249_Shoot", 10))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])	
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_M60", "Base.RF_M60mag", 100, "RF_M60_Shoot", 18))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])	
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_RPD", "Base.RF_RPDmag", 100, "RF_RPD_Shoot", 17))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_PKM", "Base.RF_PKMmag", 100, "RF_PKM_Shoot", 15))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RF_MG42", "Base.RF_MG42mag", 75, "RF_MG42_Shoot", 9))
	
end
	
if getActivatedMods():contains("\\Guns93TestB42") then	--b42
	print ("loading guns93 b42")

	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol", "Base.9mmClip", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Beretta92FS", "Base.9mmClip", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol2", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Gov1911", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Longslide", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Command1911", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Officer1911", "Base.OfficerMag", 6, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Javelina", "Base.DeltaEliteMag", 8, "MagnumShoot", 47))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.DeltaElite", "Base.DeltaEliteMag", 8, "MagnumShoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol3", "Base.44Clip", 8, "DesertEagleShoot", 45))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.BHP", "Base.BHPMag", 13, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Glock17", "Base.G17Mag", 17, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Glock22", "Base.G22Mag", 15, "M9Shoot", 36))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Glock21", "Base.G21Mag", 13, "M1911Shoot", 38))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Glock20", "Base.G20Mag", 15, "MagnumShoot", 38))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.SW5906", "Base.5906Mag", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.SW4506", "Base.4506Mag", 8, "M1911Shoot", 47))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.SW4006", "Base.4006Mag", 11, "M9Shoot", 36))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RugP89", "Base.P89Mag", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.RugP90", "BaseP90Mag", 8, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.P226", "Base.P226Mag", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.P228", "Base.P228Mag", 13, "M9Shoot", 35))
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.P7M8", "Base.P7M8Mag", 8, "M9Shoot", 35))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.P7M13", "Base.P7M13Mag", 13, "M9Shoot", 35))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.USP9", "Base.USP9Mag", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.USP40", "Base.USP40Mag", 13, "M9Shoot", 36))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.CZ75B", "Base.CZ75BMag", 16, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Raven25", "Base.R25Mag", 6, "22shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.J22", "Base.J22Mag", 6, "22shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.P380", "Base.P380Mag", 5, "M36Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.83Cheetah", "Base.83Mag", 7, "M36Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Hammerless", "Base.1908Mag", 6, "M36Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.PPK", "Base.PPKMag", 6, "M36Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Bobcat", "Base.BobcatMag", 7, "22shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])	
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Buckmark", "Base.BuckMag", 10, "22shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Rugmark", "Base.MarkMag", 10, "22shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
						
	--semi SMG
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.TEC9", "Base.TEC9Mag", 32, "M9Shoot", 35))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Uzi", "Base.UziMag", 32, "M9Shoot", 35))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.MAC10", "Base.MAC10Mag", 30, "1911Shoot", 38))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.CalicoPistol", "Base.CalicoMag", 50, "M9Shoot", 35))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])

	
	--bolt action
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.R223Rem788", "Base.223RemMag", 4, "MSR700Shoot", 120))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.HuntingRifle", "Base.308Clip", 4, "MSR788Shoot", 120))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Win69", "Base.Win69AMag", 5, "22shoot", 120))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	
	--semi automatic
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle2", "Base.M14Clip", 20, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M1A", "Base.M14Clip", 20, "M14Shoot", 38))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.FAL", "Base.FALMag", 20, "M14Shoot", 38))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.HK91", "Base.HK91Mag", 20, "M16Shoot", 38))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AR15", "Base.556Clip", 30, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.CAR15", "Base.556Clip", 30, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AR180", "Base.AR180Mag", 30, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Mini14", "Base.Mini14Mag", 20, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Mini30", "Base.Mini30Mag", 20, "MagnumShoot", 36))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AKM", "Base.AKMag", 30, "MagnumShoot", 36))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AKMS", "Base.AKMag", 30, "MagnumShoot", 36))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.T56", "Base.AKMag", 30, "MagnumShoot", 36))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Valmet", "Base.ValmetMag", 30, "M16Shoot", 35))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Rug1022", "Base.1022Mag", 10, "22shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Marlin45", "Base.45Clip", 7, "M1911Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Marlin9", "Base.5906Mag", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.CalicoRifle", "Base.CalicoMag", 50, "M9Shoot", 35))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M1Garand", "Base.EblocClip", 8, "M14Shoot", 40))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M1Carbine", "Base.M1CarMag", 8, "M36Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Brown308BAR", "Base.308BARMag", 4, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Brown3006BAR", "Base.3006BARMag", 4, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							--table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Win30067400", "Base.3006WinMag", 4, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Win3087400", "Base.308WinMag", 4, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							--table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Rem3006760", "Base.3006Rem760Mag", 4, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							--table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Rem308760", "Base.308Rem760Mag", 4, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							--table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Rem223760", "Base.223Rem760Mag", 4, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
						
	--auto SMG
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M635", "Base.ColtSMGMag", 32, "M9Shoot", 12))
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP5", "Base.MP5Mag", 30, "M9Shoot", 12))
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.M3GreaseGun", "Base.M3GreaseMag", 30, "M1911Shoot", 25))
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
			
	--automatic
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M723", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M733", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
	--MG
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M249", "Base.M249Box", 200, "M16Shoot", 10))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M60", "Base.M60Box", 100, "M14Shoot", 18))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
end

if getActivatedMods():contains("\\2256623447/firearmmod") then	--b42
	print ("loading firearm b42")

	--handgun
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol", "Base.9mmClip", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Glock17", "Base.Glock17Mag", 17, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol2", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol3", "Base.44Clip", 8, "DesertEagleShoot", 45))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.ICA19", "Base.45Clip", 7, "DesertEagleShoot", 47))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.ICA19_Gold", "Base.45Clip", 7, "DesertEagleShoot", 47))
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.ColtAce", "Base.22Clip", 10, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])

	--bolt action rifle
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.VarmintRifle", "Base.223Clip", 10, "MSR700Shoot", 120))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							
	--semi rifle
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AR15", "Base.556Clip", 30, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle2", "Base.M14Clip", 20, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M1Garand", "Base.M1GarandClip", 8, "MSR700Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])

	--SMG
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Mac10", "Base.Mac10Mag", 30, "M9Shoot", 10))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP5", "Base.MP5Mag", 30, "M9Shoot", 12))
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP5SD", "Base.MP5Mag", 30, "Firearm9mmSuppressed", 12))
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP510", "Base.MP510Mag", 30, "Firearm9mmSuppressed", 12))
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.UZI", "Base.UZIMag", 25, "M9Shoot", 17))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])

	--auto rifle
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M16A2", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M733", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.FN_FAL", "Base.FN_FAL_Mag", 20, "M16Shoot", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.G3", "Base.G3_Mag", 20, "M16Shoot", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AK47", "Base.AK_Mag", 30, "M16Shoot", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
	--MG
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M60", "Base.M60Mag", 100, "M16Shoot", 18))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])

end
	
if getActivatedMods():contains("\\url=https://steamcommunity.com/sharedfiles/filedetails/?2874163136") then		--b42/b41
	print ("loading captainjuezo firearms")	
	
	--handgun
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol", "Base.9mmClip", 15, "o_BerettaM9_o", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.cj_glock_17", "Base.MagGlock17", 17, "o_Pistol_L_o", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.cj_hi_power", "Base.MagHi-Power", 10, "o_Pistol_L_o", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.cj_p226", "Base.MagP226", 15, "o_Pistol_L_o", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol2", "Base.45Clip", 7, "o_M1911_o", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol3", "Base.44Clip", 8, "o_DE_o", 45))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.cj_walther_pp", "Base.MagWalther_PP", 7, "o_WaltherPP_o", 35))	
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.cj_intratec_9", "Base.MagTEC", 20, "o_TEC9_o", 35))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	
	--boltaction
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_ai_awp", "Base.MagAI_AW", 10, "o_AI_AWP_o", 120))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_hecate_pm", "Base.MagHecat", 7, "o_Barret_M82_o", 150))
	
	--semi auto
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_mini_14", "Base.MagMini14", 10, "o_M1A_o", 36))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_sr_25", "Base.MagSR25", 10, "o_SR25_o", 38))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_svd", "Base.MagSVD", 10, "o_SVD_o", 38))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_m1a", "Base.MagM1A", 20, "o_M1A_o", 38))
							table.insert(BanditWeapons.PolicePrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_wa_2000", "Base.MagWA2000", 6, "o_WA2000_o", 38))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_vepr_aurora", "Base.MagVepr", 20, "o_SR25_o", 38))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle2", "Base.M14Clip", 20, "o_M14_o", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_m82a1", "Base.MagM82A1", 10, "o_Barret_M82_o", 110))
	
	--SMG
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_m1928a1", "Base.MagM1928A1", 20, "o_M1928A1_o", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_mp5sd2", "Base.MagMP5SD2", 30, "o_MP5SD2_o", 12))
	
	--auto rifle
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_ak74_aurora", "Base.MagAK74M", 30, "o_AK_o", 17))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_ak74_aurora_folded", "Base.MagAK74M", 30, "o_AK_o", 17))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_ak74_m", "Base.MagAK74M", 30, "o_AK_o", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_aks74_u", "Base.MagAK74M", 30, "o_AKSU_o", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_asval", "Base.MagVSS", 10, "o_VSS_o", 17))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_aug", "Base.556Clip", 30, "o_AUG_o", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_daewoo_k2", "Base.223Clip30rnd_US", 30, "o_Daewoo_K2_o", 15))
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_g3a3", "Base.MagG3A3", 20, "o_G3A3_o", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_l85a1", "Base.556Clip", 30, "o_L85A1_o", 15))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_m4_carbine", "Base.556Clip", 30, "o_M4_o", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_sg552_commando", "Base.556Clip", 30, "o_SG552_o", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_type_81", "Base.762_39Clip30rnd_RU", 30, "o_Type81_o", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_vss", "Base.MagVSS", 10, "o_VSS_o", 17))
	
	--mg
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_m60", "Base.MagM60", 100, "o_M60_o", 18))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_m249_para", "Base.MagM249", 200, "o_M249_o", 15))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_pk", "Base.MagPK", 200, "o_PK_o", 15))
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.cj_rpk_74", "Base.MagAK74M", 30, "o_RPK_o", 17))
	
end

if getActivatedMods():contains("\\B42RainsFirearmsAndGunParts") then		--b42
	print ("loading B42 Rains Firearms")
		
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol", "Base.9mmClip", 15, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol2", "Base.45Clip", 7, "M1911Shoot", 47))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.MilitarySecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
	table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Pistol3", "Base.44Clip", 8, "DesertEagleShoot", 45))
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.Glock17", "Base.GlockMagazine", 17, "M9Shoot", 35))
							table.insert(BanditWeapons.CivilianSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.ExoticSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
							table.insert(BanditWeapons.LootedSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.HKUSP", "Base.USPClip", 12, "M1911Shoot", 38))
							table.insert(BanditWeapons.PoliceSecondary, BanditWeapons.Secondary[#BanditWeapons.Secondary])
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.HKM23", "Base.USPClip", 12, "M1911Shoot", 38))
	
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AR15", "Base.556Clip", 30, "M16Shoot", 35))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle2", "Base.M14Clip", 20, "M14Shoot", 38))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.HuntingRifle", "Base.308Clip", 5, "MSR788Shoot", 120))
							table.insert(BanditWeapons.CivilianPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
	
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.UZI", "Base.9mm30Magazine", 30, "M9Shoot", 17))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])	
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])	
    table.insert(BanditWeapons.Secondary, BanditWeapons.MakeHandgun("Base.MAC10", "Base.MAC10Clip", 30, "M1911Shoot", 10))
							table.insert(BanditWeapons.ExoticSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])	
							table.insert(BanditWeapons.LootedSecondarySpecial, BanditWeapons.Secondary[#BanditWeapons.Secondary])	
	
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP5", "Base.9mm30Magazine", 30, "M9Shoot", 12))
							table.insert(BanditWeapons.PolicePrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP5SD", "Base.9mm30Magazine", 30, "9mmSuppressed", 12))
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Thompson", "Base.ThompsonClip", 30, "M1911Shoot", 12))
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AK47", "Base.762x39Clip", 30, "MagnumShoot", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.RK62", "Base.762x39Clip", 30, "MagnumShoot", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M16A1", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.AssaultRifle", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.ColtCommando", "Base.556Clip", 30, "M16Shoot", 12))
							table.insert(BanditWeapons.MilitaryPrimary, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Galil", "Base.556Clip50", 50, "DesertEagleShoot", 17))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.G3", "Base.M14Clip", 20, "M14Shoot", 15))
							table.insert(BanditWeapons.ExoticPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
							table.insert(BanditWeapons.LootedPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M60", "Base.M60Clip", 100, "MSR788Shoot", 18))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.M249", "Base.M249Clip", 100, "MSR700Shoot", 10))
							table.insert(BanditWeapons.MilitaryPrimarySpecial, BanditWeapons.Primary[#BanditWeapons.Primary])
	
end

--[[
endif getActivatedMods():contains("MHFirearmsBeta") then	
	
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Thompson", "Base.ThompsonClip", 30, "ThompsonShoot", 12))
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.FN_P90", "Base.FNP90Magazine", 50, "P90Shoot", 10))
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.MP18", "Base.MP18Magazine", 32, "MP18Shoot", 20))						--x
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.Hellriegel", "Base.HellriegelMagazine", 120, "HellriegelShoot", 18))	--x
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.VillarPerosa", "Base.VillarPerosaMagazine", 50, "VillarShoot", 5))		--x
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.BerylM762", "Base.BerylMagazine", 30, "BerylShoot", 14))
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.FedorovAvtomat", "Base.FedorovMagazine", 25, "FedorovShoot", 21))		--x
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.FAMAS", "Base.FAMASMagazine", 30, "M16Shoot", 10))
    table.insert(BanditWeapons.Primary, BanditWeapons.MakeHandgun("Base.G36", "Base.G36Magazine", 30, "M16Shoot", 12))
	
end
--]]

